# Generated by Django 2.0 on 2018-07-06 03:24

import abstract.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import functools


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default=None, help_text='Please explain why you are applying for this scholarship. This field is limited to 200 words or less.', validators=[functools.partial(abstract.validators.validate_n_word_or_less, *(), **{'n': 200})], verbose_name='Reason')),
                ('has_other_funding', models.BooleanField(default=False, verbose_name='Do you have any other sources of funding?')),
                ('other_funding', models.TextField(blank=True, default=None, help_text='Please list any additional sources of funding if applicable.', null=True, verbose_name='Reason')),
                ('submitter', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
