# Generated by Django 2.0 on 2018-07-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_scholarshipapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='other_funding',
            field=models.TextField(blank=True, default=None, help_text='Please list any additional sources of funding if applicable.', null=True, verbose_name='List of other funding sources'),
        ),
    ]
