# Generated by Django 2.0 on 2018-07-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0015_auto_20180709_1921'),
        ('account', '0003_auto_20180706_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='keywords',
            field=models.ManyToManyField(help_text='Describe your expertise with a few keywords. You may enter keywords that do not appear in this list by pressing the Return/Enter on your keyboard. These keywordsmay affect which abstracts are assigned to you for review', related_name='profiles', related_query_name='profile', to='abstract.Keyword', verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='affiliation',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name='Primary Affiliation'),
        ),
    ]
