# Generated by Django 2.0 on 2018-07-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180709_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='keywords',
            field=models.ManyToManyField(help_text='Describe your expertise with a few keywords. You may enter keywords that do not appear in this list by pressing the Return/Enter on your keyboard.', related_name='profiles', related_query_name='profile', to='abstract.Keyword', verbose_name='Keywords'),
        ),
    ]
