# Generated by Django 2.0 on 2018-08-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180710_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True, unique=True, verbose_name='Email address'),
        ),
    ]
