# Generated by Django 2.0 on 2018-09-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20180808_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True, verbose_name='Email address'),
        ),
    ]
