# Generated by Django 2.0 on 2018-07-06 03:24

import abstract.validators
import django.core.validators
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0006_auto_20180705_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='author_affiliations',
            field=models.TextField(blank=True, default=None, help_text='Please list the primary affiliations of all contributing authors including yourself (comma separated).', verbose_name='Contributing author affiliations'),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='authors',
            field=models.TextField(blank=True, default=None, help_text='Please list all contributing authors including yourself (comma separated).', verbose_name='Contributing authors'),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='keywords',
            field=models.ManyToManyField(help_text='Please assign a few keywords to your abstract. You may enter keywords that do not appear in this list by pressing the Return/Enter on your keyboard.', related_name='abstracts', related_query_name='abstract', to='abstract.Keyword', verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='title',
            field=models.TextField(default=None, help_text='Please title your abstract using 20 words or less.', validators=[functools.partial(abstract.validators.validate_n_word_or_less, *(), **{'n': 30})], verbose_name='Abstract title'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='score_content',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)], verbose_name="Score based on the abstract's scientific content."),
        ),
        migrations.AlterField(
            model_name='comment',
            name='score_contribution',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)], verbose_name="Score based on the author's contribution to the work."),
        ),
        migrations.AlterField(
            model_name='comment',
            name='score_interest',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)], verbose_name="Score based on the ability of the abstract's contents to hold your interest."),
        ),
    ]
