# Generated by Django 2.0 on 2018-07-06 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abstract', '0008_auto_20180706_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=24, verbose_name='Status')),
                ('rejection_comment', models.TextField(blank=True, default=None, help_text='Please give a reason for rejecting this review assignment.', null=True, verbose_name='Reason')),
            ],
            options={
                'ordering': ('reviewer',),
            },
        ),
        migrations.AddField(
            model_name='abstract',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Approve?'),
        ),
        migrations.AddField(
            model_name='abstractassignment',
            name='abstract',
            field=models.ForeignKey(blank=None, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', related_query_name='assignment', to='abstract.Abstract'),
        ),
        migrations.AddField(
            model_name='abstractassignment',
            name='reviewer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', related_query_name='assignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='abstractassignment',
            unique_together={('reviewer', 'abstract')},
        ),
    ]
