# Generated by Django 2.0 on 2018-07-07 10:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0010_auto_20180707_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='review',
            field=models.ForeignKey(blank=None, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', related_query_name='assignment', to='abstract.Review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_content',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)], verbose_name="Score based on the abstract's scientific content."),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_contribution',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)], verbose_name="Score based on the author's contribution to the work."),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_interest',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)], verbose_name="Score based on the ability of the abstract's contents to hold your interest."),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(default=None, verbose_name='Review'),
        ),
    ]
