# Generated by Django 2.0 on 2018-07-08 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0012_auto_20180708_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score_content',
            field=models.IntegerField(default=None, help_text="Score based on the abstract's scientific content.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)], verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_contribution',
            field=models.IntegerField(default=None, help_text="Score based on the author's contribution to the work.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)], verbose_name='Contribution'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_interest',
            field=models.IntegerField(default=None, help_text="Score based on the ability of the abstract's contents to hold your interest.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)], verbose_name='Interest'),
        ),
    ]
