# Generated by Django 2.0 on 2018-07-08 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0013_auto_20180708_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='review',
            field=models.ForeignKey(blank=None, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', related_query_name='assignment', to='abstract.Review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(default=None, help_text='Please provide a few short comments justifying why you have given the scores above.', verbose_name='Comments'),
        ),
    ]
