# Generated by Django 2.0 on 2018-07-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0014_auto_20180708_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='rejection_comment',
            field=models.TextField(default=None, help_text='Please give a reason for declining this review assignment.', null=True, verbose_name='Reason'),
        ),
    ]
