# Generated by Django 2.0 on 2018-07-10 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abstract', '0015_auto_20180709_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='created_by',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='review',
            field=models.OneToOneField(blank=None, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment', to='abstract.Review'),
        ),
    ]
