# Generated by Django 2.0 on 2018-07-10 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0016_auto_20180710_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstract',
            name='reviewers',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', related_query_name='created_assignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
