# Generated by Django 2.0 on 2018-08-08 08:44

import abstract.validators
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0018_auto_20180808_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='text',
            field=models.TextField(default=None, help_text='Please describe your abstract using 250 words or less.', validators=[functools.partial(abstract.validators.validate_n_word_or_less, *(), **{'n': 250})], verbose_name='Abstract'),
        ),
    ]
