# Generated by Django 2.0 on 2018-09-16 12:09

import abstract.validators
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0019_auto_20180808_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationcategory',
            name='closing_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='title',
            field=models.TextField(default=None, help_text='Please title your abstract using 30 words or less.', validators=[functools.partial(abstract.validators.validate_n_word_or_less, *(), **{'n': 30})], verbose_name='Abstract title'),
        ),
    ]
