# Generated by Django 2.0 on 2018-09-17 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0020_auto_20180916_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score_content',
            field=models.IntegerField(default=None, help_text='Score reflecting the scientific quality, importance and innovation.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)], verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_contribution',
            field=models.IntegerField(default=None, help_text="Score reflecting the author's contribution.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)], verbose_name='Contribution'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_interest',
            field=models.IntegerField(default=None, help_text='Score reflecting your interest and engagement.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)], verbose_name='Interest'),
        ),
    ]
