# Generated by Django 2.0 on 2018-09-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0021_auto_20180917_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, default=None, help_text='Please provide a few short comments justifying why you have given the scores above (optional).', null=True, verbose_name='Comments'),
        ),
    ]
