# Generated by Django 2.2.20 on 2021-05-26 03:45

import abstract.validators
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0022_auto_20180917_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='accepted',
            field=models.BooleanField(blank=True, default=False, verbose_name='Approve?'),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='contribution',
            field=models.TextField(default=None, help_text='Please describe your contribution to the research detailed in your abstract using 100 words or less.', validators=[functools.partial(abstract.validators.validate_n_word_or_less, *(), **{'n': 130})], verbose_name='Your contribution'),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='text',
            field=models.TextField(default=None, help_text='Please describe your abstract using 250 words or less.', validators=[functools.partial(abstract.validators.validate_n_word_or_less, *(), **{'n': 300})], verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='title',
            field=models.TextField(default=None, help_text='Please title your abstract using 30 words or less.', validators=[functools.partial(abstract.validators.validate_n_word_or_less, *(), **{'n': 35})], verbose_name='Abstract title'),
        ),
    ]
