version: "3"

services:
  app:
    image: abacbs/absss:latest
    build:
      context: .
    volumes:
      - $PWD:/srv/app
    environment:
      - ENVIRONMENT=production
      - GUNICORN_WORKERS=2
      - GUNICORN_THREADS=4
      - DJANGO_SETTINGS_MODULE=settings.production

  server:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/static:/srv/app/static/
      - $PWD/logs:/var/log/nginx:rw
      - $PWD/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - $PWD/docker/nginx/ssl:/etc/nginx/certs:ro
