# Generated by Django 2.0.6 on 2018-07-02 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careerstage',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AddField(
            model_name='careerstage',
            name='creation_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Creation date'),
        ),
        migrations.AddField(
            model_name='careerstage',
            name='modification_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Modification date'),
        ),
        migrations.AddField(
            model_name='gender',
            name='creation_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Creation date'),
        ),
        migrations.AddField(
            model_name='gender',
            name='modification_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Modification date'),
        ),
        migrations.AddField(
            model_name='state',
            name='creation_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Creation date'),
        ),
        migrations.AddField(
            model_name='state',
            name='modification_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='careerstage',
            name='name',
            field=models.CharField(default=None, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='gender',
            name='type',
            field=models.CharField(default=None, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(default=None, max_length=128, unique=True),
        ),
    ]
